### ISSUE TITLE
Error compilation on manip-waiter repo

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/manip-waiter#1]
_From @jlpesoto on February 8, 2018 17:5_

there is an error compilation on manip-waiter repo (branch: jr3) related with ICartesianSolver.h

In file included from /home/teo/repos/manip-waiter/programs/jr3WristControl/InCvPort.cpp:3:0:
/home/teo/repos/manip-waiter/programs/jr3WristControl/InCvPort.hpp:14:30: fatal error: ICartesianSolver.h: No such file or directory
compilation terminated.
programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/build.make:62: recipe for target 'programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/InCvPort.cpp.o' failed
make[2]: *** [programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/InCvPort.cpp.o] Error 1
CMakeFiles/Makefile2:332: recipe for target 'programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/all' failed
make[1]: *** [programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

_Copied from original issue: roboticslab-uc3m/teo-main#36_

**Comment by jgvictores** [comment]
_From @PeterBowman on February 8, 2018 17:10_

> ICartesianSolver.h

This header is shipped with the [kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics/) repo. Please follow the installation guides, you should end up with ICartesianSolver.h in /usr/local/include.

**Comment by jgvictores** [comment]
_From @jmgarciah on February 8, 2018 17:23_

A new error appears related with ColorDebug.hpp:

/home/teo/repos/manip-waiter/programs/jr3WristControl/InCvPort.hpp:16:26: fatal error: ColorDebug.hpp: No such file or directory
compilation terminated.
programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/build.make:62: recipe for target 'programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/InCvPort.cpp.o' failed
make[2]: *** [programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/InCvPort.cpp.o] Error 1
CMakeFiles/Makefile2:329: recipe for target 'programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/all' failed
make[1]: *** [programs/jr3WristControl/CMakeFiles/jr3WristControl.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jgvictores** [comment]
The basic file that needs updating is: https://github.com/roboticslab-uc3m/manip-waiter/blob/665e740c158cc9c93567d38237835e729c5352be/programs/jr3WristControl/CMakeLists.txt

Essentially, you need some `find_package()` and all related cmake commands. For inspiration:
- https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/example/cpp/exampleCanBusControlboard/CMakeLists.txt#L6
- https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/develop/example/cpp/exampleCartesianControlClient/CMakeLists.txt#L7

**Comment by jmgarciah** [comment]
solved

**Comment by jmgarciah** [comment]
Solved via 54c0b3c244e1b9e409d322d19fea5c1a6468853c and f93e5dcef89d541acfa6eda5072083310c80ae7d
