### ISSUE TITLE
IAnalogSensor::calibrateSensor always reports a failure

### ISSUE THREAD

**Issue by jmgarciah** [roboticslab-uc3m/manip-waiter#2]
In the program "testCap52", It is defined the leftArm and the trunk devices. Also, we include the analogSensorClient to use jr3, like the [exampleRemoteJr3](https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/examples/cpp/exampleRemoteJr3/exampleRemoteJr3.cpp)

The program gives an error when it tries to execute [calibrateChannel()](http://yarp.it/classyarp_1_1dev_1_1IAnalogSensor.html#ab69a5e6e94476ec8efdc2e656b64afa1)

The same problem happens with calibrateSensor()

**Comment by jmgarciah** [comment]
checking the repo yarp-devices with @PeterBowman , it is detected same errors in the return value for the analogServer implementation. And also, in analogsensorclient, the return value is changed from int to bool (YARP 2.3.70/2.3.72.1, e.g. see [ref](https://github.com/robotology/yarp/blob/v2.3.70.2/src/libYARP_dev/src/devices/AnalogSensorClient/AnalogSensorClient.cpp#L252-L259) + [ref](https://github.com/robotology/yarp/blob/v2.3.70.2/src/libYARP_dev/include/yarp/dev/ControlBoardHelpers.h#L23-L34))

**Comment by jgvictores** [comment]
Anything to do here at [roboticslab-uc3m/yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices) level (to open an issue over there)?

**Comment by PeterBowman** [comment]
This is an upstream bug detected in https://github.com/roboticslab-uc3m/WBPCwaiter/commit/63bab1c1132ed443f8144e82d3667fb8d512b295#diff-435075293a7226d2e50af7998bf9bb43R426 and reported at https://github.com/robotology/yarp/issues/1981. All we can do for now is to recommend avoiding such sanity checks (the return value is bogus).

> Anything to do here at [roboticslab-uc3m/yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices) level (to open an issue over there)?

No, this actually deserves an *upstream* or *resolution: upstream* label.

**Comment by PeterBowman** [comment]
Fixed in current YARP devel (v3.2.0, unreleased).
